[package]
name = "harfbuzz_rs"
version = "0.1.0"
authors = ["Manuel Reinhardt <manuel.jr16@gmail.com>"]

[dependencies]
harfbuzz-sys = { git = "https://github.com/manuel-rhdt/rust-harfbuzz.git" }
libc = "0.2.*"
rusttype = "0.2.1"
lazy_static = "0.1.*"

[dev-dependencies]
piston_window = "0.61.*"
image = "*"
pistoncore-glfw_window = "0.29.*"
